-- Per operator (2026-06-05): replacement orders that already shipped
-- (have a tracking number, or notes say "dropped off" via personal
-- delivery) shouldn't sit in the in-app approval/fulfillment pipeline.
-- They belong in the historical record (fulfillment_log) so operators
-- can look them up, but the active Replacement queue should only show
-- replacements that still need work.
--
-- Two actions:
--   1. Re-import the Replacement tab of LILA customer fulfillment-20260605.xlsx
--      into public.fulfillment_log with FULL data (tracking, carrier,
--      price, dates, notes). The previous June 3 import only captured
--      customer_name + serial_number on most rows.
--   2. Delete the 10 already-shipped replacement orders from
--      public.orders. They were imported as kind='replacement' by
--      migration 20260605080000; that migration stays (idempotent on
--      conflict) but these specific shipped rows get pruned. Pending
--      ones (no tracking) remain in orders for the active workflow.
--
-- service_tickets.replacement_order_id has ON DELETE SET NULL so the
-- ticket linkage clears automatically.

delete from public.fulfillment_log where source_tab = 'Replacement';

insert into public.fulfillment_log (
  source_tab, source_row, shipping_date, ticket_date,
  customer_name, address, phone, email, batch, color, serial_number,
  tracking_number, carrier, price, update_status, notes, raw
) values
  ('Replacement', 2,  null,         '2026-04-22', 'Jake Wenger',                       '20757 Atlantic Puffin Dr, Grand Rapids, MN 55744, USA',   '218-301-4249', 'wenger.jake@gmail.com',          'both side latch',                     null,    null,                  null,                       null,           null,    null,                       null, '{}'::jsonb),
  ('Replacement', 3,  '2026-05-07', '2026-04-24', 'Brittany Hemenway',                 '14032 Crested Moss Ct, Reno, NV, 89511, USA',             '775-250-8351', 'bnhemenway@gmail.com',           'P100',                                'White', 'LL01-00000000271',    '1ZV56D26DK26632644',       'UPS',          195.44,  'Received (05/14/2026)',    'Replacement', '{}'::jsonb),
  ('Replacement', 4,  '2026-05-07', null,         'Rebecca Campbell',                  '304-716 Old Sackville Rd., Lower Sackville, NS, B4C 2K3', '902-818-8352', 'campbellra652@gmail.com',        'P100',                                'White', 'LL01-00000000307',    'D420352470002152685001',   'Canpar',       94.67,   'Received (05/12/2026)',    null, '{}'::jsonb),
  ('Replacement', 5,  null,         null,         'Annmarie Kennedy',                  '32 Walnut St, Seymour, CT, 06483, USA',                   '203-895-2263', 'anmarik@comcast.net',            'side latch (?) and filter cup',       null,    null,                  null,                       null,           null,    null,                       'Raymond Zhu High priority', '{}'::jsonb),
  ('Replacement', 6,  '2026-05-15', '2026-04-18', 'Gina Daniels',                      '3102 Tinamous Rd, Eagle Mountain, UT, 84005, USA',        '208-409-3929', 'gdaniels@mw.foreverlawn.com',    'P100',                                null,    'LL01-00000000297',    '1ZV56D26DK16622254',       'UPS',          198.83,  'Received (5/21/2026)',     'Raymond Zhu High priority', '{}'::jsonb),
  ('Replacement', 7,  null,         null,         'Suzanne McRae',                     '43 Peak Point Blvd, Maple, ON, Canada',                   '416-624-9647', 'suemmcrae@gmail.com',            'broken compost chamber (right side)', null,    null,                  null,                       null,           null,    null,                       null, '{}'::jsonb),
  ('Replacement', 8,  null,         null,         'Dale Bober',                        '4021 Palo Alto Ave, Yucca Valley, CA, 92284, USA',        '760-799-9286', 'dalebober@gmail.com',            'side latch (? side)',                 null,    null,                  null,                       null,           null,    null,                       null, '{}'::jsonb),
  ('Replacement', 9,  '2026-05-19', null,         'Chris & Renata Grant',              '3 Father Redmond Way, Etobicoke, ON M8W 0B4',             '905-301-7988', 'cb.grant@hotmail.com',           'P100',                                null,    'LL01-00000000288',    'dropped off',              null,           null,    'Received',                 'Personal Delivery', '{}'::jsonb),
  ('Replacement', 10, '2026-05-11', null,         'Jason Amero',                       null,                                                      null,           null,                             'both compost chambers cracked',       null,    null,                  null,                       null,           null,    null,                       'Personal Delivery', '{}'::jsonb),
  ('Replacement', 11, null,         '2026-05-11', 'Mark Marshall',                     '675369 16th Line Innerkip ON N0J 1M0',                    '519-533-8989', 'm.c.marshall@sympatico.ca',      'P100 X',                              null,    null,                  null,                       null,           null,    null,                       null, '{}'::jsonb),
  ('Replacement', 12, null,         '2026-05-11', 'Brent Baker (Neave)',               '4506 Grizzly Hill Rd., Spallumcheen, BC, V4Y 0M1',        '(604) 329-2421', 'brent@baker-neave.com',        'right side latch',                    null,    null,                  '104504378910343',          'Canada Post',  16.39,   null,                       null, '{}'::jsonb),
  ('Replacement', 13, null,         '2026-05-11', 'Leen Schafer',                      '7367 Kamwood Street, San Diego, CA, 92126, USA',          '(949) 554-9788', 'leenschafer@gmail.com',        'left side chamber',                   null,    null,                  null,                       null,           null,    null,                       null, '{}'::jsonb),
  ('Replacement', 14, null,         '2026-05-11', 'Donna Wood',                        '6 Buchanan Cres, Thorold, ON, Canada',                    '905-330-5289', 'smilesarefree6@gmail.com',       'starter bags',                        null,    null,                  '104504378991342',          'Canada Post',  22.95,   null,                       null, '{}'::jsonb),
  ('Replacement', 15, null,         '2026-04-20', 'Tony Rinella',                      '16 Marianfeld Ave Toronto ON M6B 3W3',                    '416-783-2550', 'rinellat@hotmail.com',           'P150',                                null,    null,                  null,                       null,           null,    null,                       null, '{}'::jsonb),
  ('Replacement', 16, '2026-05-19', '2026-03-23', 'Kevin Cheng',                       '15 Charlotte Angliss Road Markham ON L3P 7W6',            '416-887-4779', 'ziontkd.markham@gmail.com',      'P100',                                null,    'LL01-00000000341',    'dropped off',              null,           null,    'Received',                 'Raymond Zhu High priority, Personal Delivery', '{}'::jsonb),
  ('Replacement', 17, null,         '2026-04-22', 'Angeline Purcell',                  '499 Main St, Elsipogtog First Nation, NB, E4W 2X5',       '506-523-7006', 'annpurcell123@hotmail.com',      'P150',                                null,    null,                  null,                       null,           null,    null,                       null, '{}'::jsonb),
  ('Replacement', 18, null,         null,         'Scott Gilbert & Karolina Chmiel',   null,                                                      null,           null,                             'P100X',                               null,    null,                  null,                       null,           null,    null,                       null, '{}'::jsonb),
  ('Replacement', 19, '2026-05-15', null,         'Jeffrey Van Dyke',                  '731 E Twin Palms Dr, Palm Springs, CA, 92264, USA',       '971-344-2438', 'jeffreyvandyke@comcast.net',     'P100',                                null,    'LL01-00000000304',    '1ZV56D26DK26566350',       'UPS',          204.27,  'Received (5/22/2026)',     'Raymond Zhu High priority', '{}'::jsonb),
  ('Replacement', 20, null,         null,         'Tien Tran',                         null,                                                      null,           null,                             'P150',                                null,    null,                  null,                       null,           null,    null,                       null, '{}'::jsonb),
  ('Replacement', 21, null,         null,         'Michael Madigan',                   null,                                                      null,           null,                             'P150',                                null,    null,                  null,                       null,           null,    null,                       null, '{}'::jsonb),
  ('Replacement', 22, null,         null,         'Tamara Martin',                     null,                                                      null,           null,                             'P100',                                null,    null,                  null,                       null,           null,    null,                       'Raymond Zhu High priority', '{}'::jsonb),
  ('Replacement', 23, null,         null,         'Candace Chan',                      null,                                                      null,           null,                             'P150',                                null,    null,                  null,                       null,           null,    null,                       null, '{}'::jsonb),
  ('Replacement', 24, '2026-06-04', null,         'Ellery Bunn',                       '182 Southcrest Dr, Seagrave, ON L0C 1G0',                 '416-797-9143', 'ellery.bunn@gmail.com',          'P150',                                'White', 'LL01-00000000150',    'D420352470002273178001',   'Canpar',       76.90,   null,                       'Raymond Zhu High priority', '{}'::jsonb),
  ('Replacement', 25, null,         null,         'Brian Fryer',                       null,                                                      null,           null,                             'P100',                                null,    null,                  null,                       null,           null,    null,                       null, '{}'::jsonb),
  ('Replacement', 26, null,         null,         'Connie Beatty',                     null,                                                      null,           null,                             'P150',                                null,    null,                  null,                       null,           null,    null,                       null, '{}'::jsonb),
  ('Replacement', 27, null,         null,         'Fred Rice',                         '6284 Smith Rd, Hamburg, NY, 14075, USA',                  '814-688-7182', 'ricefj50@yahoo.com',             'Replacement top lid',                 null,    null,                  null,                       null,           null,    null,                       null, '{}'::jsonb),
  ('Replacement', 28, null,         null,         'Patrick Taylor',                    null,                                                      null,           null,                             'Right side latch',                    null,    null,                  null,                       null,           null,    null,                       null, '{}'::jsonb),
  ('Replacement', 29, null,         '2026-05-25', 'Shearries Moseley Lafontaine',      null,                                                      null,           'shearries@gmail.com',            'unspecified parts',                   null,    null,                  null,                       null,           null,    null,                       'Order #1155 -- Unit cracked on arrival; awaiting packaging photos for insurance claim', '{}'::jsonb),
  ('Replacement', 30, null,         '2026-05-24', 'Jeff Carnahan',                     null,                                                      '236-333-6787', 'worldcoast@gmail.com',           'unspecified parts',                   null,    null,                  null,                       null,           null,    null,                       'Order #1134 -- Plastic split; replacement scheduled with next batch. HS-0113.', '{}'::jsonb),
  ('Replacement', 31, null,         '2026-06-01', 'Vicki Myhre',                       '115 Hillview Rd, Strathmore, AB, T1P 1W2',                '403-901-9472', 'svmyhre@shaw.ca',                'Side latch + compost chambers',       null,    null,                  null,                       null,           null,    null,                       null, '{}'::jsonb),
  ('Replacement', 32, '2026-06-04', '2026-05-31', 'Judy Mahon',                        '2562 Cornerstone Ct, West Kelowna, BC, V4T 2Y3',          '306-441-7110', 'judymml@sasktel.net',            'Hopper',                              null,    null,                  '1ZV56D262027006405',       'UPS',          21.71,   null,                       null, '{}'::jsonb);

-- Prune the shipped replacement orders from the active pipeline.
-- service_tickets.replacement_order_id has ON DELETE SET NULL so any
-- ticket linkage clears automatically.
delete from public.orders
where kind = 'replacement'
  and tracking_num is not null;
