-- RBAC substrate (Huayi P1 S — Phase A of the substrate week).
-- See docs/session-notes/huayi.md §Feature 1.
--
-- Three things:
--   1. Promote profiles.role from free-text (default 'member') to a typed
--      enum user_role ('operator','manager','finance','admin'), so
--      lib/permissions.ts canDo()/canView() helpers have a single source
--      of truth instead of the hard-coded MANAGER_EMAILS / FINANCE_EMAILS
--      arrays currently in lib/postShipment.ts. Use alter-column-type
--      with a cast so the column ACLs from the recent security fix
--      (20260605140000) carry through untouched.
--
--   2. Add SECURITY DEFINER helpers current_user_role(), is_manager(),
--      is_finance() that RLS policies can call. Mirror the style of
--      is_internal_user() from 20260603200000_profiles_is_internal.sql.
--
--   3. Tighten the refund_approvals UPDATE policy so manager-stage and
--      finance-stage write requires is_manager() in WITH CHECK (the
--      existing policy from 20260604200000_rls_internal_only.sql:255-258
--      only enforced is_internal_user() — any internal teammate could
--      flip the finance fields). SELECT is unchanged.
--
-- Two data fixes piggyback (single-row, idempotent):
--   - Yueli (Julie)'s existing profile.display_name updated from
--     "Yueli Li" to "Julie" matching team_invite_list.
--   - Yueli backfilled into finance role alongside George + Huayi.
--
-- Out of scope for Phase A:
--   - Manager role is intentionally NOT seeded — overlap with finance
--     (George is on both lists today) covers the only manager today.
--     When an ops-floor manager joins, flip them via a one-row UPDATE.
--   - Other tables' RLS stays as-is. Tightening service_tickets / units
--     etc to consult is_manager() is deferred until those write paths
--     adopt canDo() in their own modules.
--
-- Rollback note: do NOT edit this file once applied. If a critical bug
-- surfaces, write an inverse migration. Risk is low: blast radius is
-- "non-managers cannot UPDATE refund_approvals", and today only
-- modules/PostShipment/RefundsTab.tsx issues those updates and already
-- gates on manager/finance email at the UI.

-- ─── 1. Display-name fix for Yueli ──────────────────────────────────────
update public.profiles p
   set display_name = 'Julie'
  from auth.users u
 where u.id = p.id
   and lower(u.email) = 'yueli@virgohome.io';

-- ─── 2. user_role enum ──────────────────────────────────────────────────
create type public.user_role as enum ('operator','manager','finance','admin');

-- ─── 3. Normalize legacy values + cast column ───────────────────────────
-- Existing rows have role='member' (the old default). 'member' isn't
-- in the enum — normalize first so the cast doesn't fail.
update public.profiles
   set role = 'operator'
 where role is null or role not in ('operator','manager','finance','admin');

alter table public.profiles
  alter column role drop default;

alter table public.profiles
  alter column role type public.user_role using role::public.user_role;

alter table public.profiles
  alter column role set default 'operator',
  alter column role set not null;

-- ─── 4. handle_new_user trigger — set role explicitly ──────────────────
-- Trigger was last touched by 20260417023746_seed_team_invite_list.sql
-- when display_name was added; this re-creates it with role='operator'
-- so new sign-ins land in the right enum value (Postgres column default
-- handles this too, but being explicit is safer if defaults change).
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer as $$
declare override_name text;
begin
  select display_name into override_name
    from public.team_invite_list where email = new.email;
  insert into public.profiles (id, display_name, role)
  values (
    new.id,
    coalesce(override_name, new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1)),
    'operator'
  );
  return new;
end $$;

-- ─── 5. Seed finance role ──────────────────────────────────────────────
-- George + Huayi + Yueli (Julie) per current FINANCE_EMAILS in
-- lib/postShipment.ts after the 2026-06-07 julie@→yueli@ fix.
update public.profiles p
   set role = 'finance'
  from auth.users u
 where u.id = p.id
   and lower(u.email) in ('george@virgohome.io','huayi@virgohome.io','yueli@virgohome.io');

-- ─── 6. Role-check helpers (SECURITY DEFINER, STABLE) ──────────────────
create or replace function public.current_user_role()
returns public.user_role
language sql stable security definer set search_path = public as $$
  select role from public.profiles where id = auth.uid();
$$;

create or replace function public.is_finance()
returns boolean
language sql stable security definer set search_path = public as $$
  select coalesce((select role from public.profiles where id = auth.uid())
                  in ('finance','admin'), false);
$$;

create or replace function public.is_manager()
returns boolean
language sql stable security definer set search_path = public as $$
  select coalesce((select role from public.profiles where id = auth.uid())
                  in ('manager','finance','admin'), false);
$$;

grant execute on function public.current_user_role() to authenticated;
grant execute on function public.is_finance()        to authenticated;
grant execute on function public.is_manager()        to authenticated;

-- ─── 7. Tighten refund_approvals UPDATE policy ─────────────────────────
-- Existing policy "refundapprovals_update" from 20260604200000:255-258
-- was `using (is_internal_user())` with no WITH CHECK — meaning Postgres
-- inherits USING as the new-row check, so any internal user could flip
-- finance fields. Replace with explicit WITH CHECK requiring is_manager()
-- (which includes finance + admin). SELECT/INSERT/DELETE policies
-- unaffected.
drop policy if exists "refundapprovals_update" on public.refund_approvals;

create policy "refundapprovals_update"
  on public.refund_approvals for update
  to authenticated
  using (public.is_internal_user())
  with check (public.is_manager());
